version: "3"
services:
  mysql_database:
    image: mysql:8
    ports:
      - "3001:3306"
    volumes:
      - ./src/data/mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=dev_database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
  node:
    depends_on:
      - mysql_database
    build: .
    ports:
      - "3000:80"
    volumes:
      - ./src:/root/app
    environment:
      - MYSQL_DATABASE=dev_database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - NODE_ENV=dev
